### ISSUE TITLE
plz help volume24H is 0 ? is it fix?

### ISSUE THREAD

**Issue by geper** [s0h3ck/coinpaprika-api-python-client#6]
plz help volume24H is 0 ? is it fix?

**Comment by s0h3ck** [comment]
Coinpaprika may not have the data of all the cryptocurrencies on the market. Also, I do know the context of your question.

Anyway, taking bitcoin for example, it does work fine.

```python
from coinpaprika import client as Coinpaprika

client = Coinpaprika.Client()

candles = client.candles("btc-bitcoin", start="2022-01-01", limit=30, interval="24h")

for candle in candles:
    print(candle)
```

Here is a screenshot of the results.

![2022-01-18_22-04](https://user-images.githubusercontent.com/7539558/150056182-b9ac3ce4-fcdc-4d6f-8c8d-ab35963eecdc.png)

This is just a wrapper. The data is provided by Coinpaprika. If they provide no data, feel free to contact their team.

I hope it answers your question. :sunglasses:

**Comment by geper** [comment]
thank for answer
i use client.tickers() 
https://replit.com/@geper/coinap#main.py
![image](https://user-images.githubusercontent.com/1608173/150068418-6a4db1ec-3a9f-4c7b-bd5e-41af4f4b5273.png)

**Comment by geper** [comment]
i get all tickers and filters by volume24h

**Comment by s0h3ck** [comment]
I will repeat myself, but as I said, Coinpaprika is doing something wrong that is not something I can fix. It is Coinpaprika's responsibility at this point. 

You can also test and see the experimentation for yourself in the JavaScript library made by someone else.
```js
( async () => {
    const util = require('util');
    const cp = require( 'coinpaprika-js' );
    
    // Get tickers for all coins (USD,BTC,ETH)
    console.log(JSON.stringify(await cp.tickers(), null, 4));
    
} )();
```

![2022-01-19_01-25](https://user-images.githubusercontent.com/7539558/150075978-cf23c3dc-4cc9-42a4-b802-b6b583173b3a.png)

Nice catch though! :)

**Comment by geper** [comment]
thank you very much

**Comment by r--w** [comment]
Hi guys, thank you for the ticket. We heavily optimized our back-end infrastructure and introduced this bug, which is fixed now. Please feel free to contact us at support@coinpaprika.com in case of any further problems. Thank you for using API, you can close this ticket. Radek CEO@Coinpaprika

**Comment by s0h3ck** [comment]
@r--w Awesome! Ticket closed.
